addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 3dd6631d-b53a-4853-a241-3855df4eec71
after_success:
- ./df-build.sh
jdk:
- oraclejdk8
language: java
notifications: {}
# Modified by Insights Service at 2016-05-07 20:22:42.716649
